spring:
  application:
    name: TeamManagementSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/TeamManagementSystem?options=-c%20TimeZone=Europe/Kyiv
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Europe/Kyiv

  data:
    redis:
      host: localhost
      port: 6379

  docker:
    compose:
      lifecycle-management: start_only